<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1499943125263" stop="1499943646350" version="1.4.16" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Default suite : Default test</name>
    <title>Default suite : Default test</title>
    <test-cases>
        <test-case start="1499943282635" stop="1499943403537" status="passed">
            <name>Validating_feed1</name>
            <title>Validating feed_1 Ad call</title>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="vpathania-mpro.corp.weather.com"/>
                <label name="thread" value="9374@vpathania-mpro.corp.weather.com.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1499943403574" stop="1499943419326" status="passed">
            <name>Validating_feed2</name>
            <title>Validating feed_2 Ad call</title>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="vpathania-mpro.corp.weather.com"/>
                <label name="thread" value="9374@vpathania-mpro.corp.weather.com.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1499943419330" stop="1499943501795" status="failed">
            <name>Validating_feed3</name>
            <title>Validating feed_3 Ad call</title>
            <failure>
                <message>AssertionError: feed3 ad not present</message>
                <stack-trace>java.lang.AssertionError: feed3 ad not present
	at org.testng.Assert.fail(Assert.java:94)
	at twc.Automation.HandleWithAppium.AppiumFunctions.Check_feed3_ad(AppiumFunctions.java:409)
	at ANDROID_ARMS.ANDROID_ARMS.FeedAdVAlidationonUI.Validating_feed3(FeedAdVAlidationonUI.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="vpathania-mpro.corp.weather.com"/>
                <label name="thread" value="9374@vpathania-mpro.corp.weather.com.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1499943501797" stop="1499943646348" status="broken">
            <name>Validating_feed4</name>
            <title>Validating feed_3 Ad call</title>
            <failure>
                <message>Test was interrupted</message>
            </failure>
            <labels>
                <label name="host" value="vpathania-mpro.corp.weather.com"/>
                <label name="thread" value="9374@vpathania-mpro.corp.weather.com.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1499943125263" stop="1499943646348" status="broken">
            <name>Default suite : Default test</name>
            <title>Default suite : Default test</title>
            <failure>
                <message>Test suite was interrupted, some test cases may be lost</message>
            </failure>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
